name: fima
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  floating_bottom_navigation_bar: ^1.5.2
  animated_text_kit: ^4.2.2
  motion_toast: ^2.6.5
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_analytics: ^10.1.6
  url_launcher: ^6.1.10
  cloud_firestore: ^4.5.0
  zxcvbn: ^1.0.0
  firebase_storage: ^11.1.2
  cached_network_image: ^3.2.3
  path_provider: ^2.0.14
  shared_preferences: ^2.1.0
  provider: ^6.0.5
  http: ^0.13.6
  flutter_cache_manager: ^3.3.0
  image: ^4.0.17
  flutter_launcher_icons: ^0.13.1
  emoji_picker_flutter: ^1.5.4
  flutter_emoji_gif_picker: ^0.1.3
  image_picker: ^0.8.7+5
  firebase_messaging: ^14.6.1
  flutter_local_notifications: ^14.1.0
  flutterwave_standard: ^1.0.7
  intl_phone_number_input: ^0.7.3+1
  loading_animation_widget: ^1.2.0+4
  flutter_native_splash: ^2.3.1
  flutter_spinkit: ^5.2.0
  intl: ^0.18.1
  permission_handler: ^10.4.1
  google_fonts: ^4.0.4
  ticket_widget: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/fimalogo.png
      - assets/images/qrid.png
      - assets/images/notification.png
      - assets/images/password.png
      - assets/images/verify.png
      - assets/images/id.png
      - assets/images/split.png
      - assets/images/wallet.png
      - assets/images/chart.png
      - assets/images/sim.png
      - assets/images/mobile-data.png
      - assets/images/check.png
      - assets/images/fingerprint.png
      - assets/images/validate.png
      - assets/images/clear.png
      - assets/images/paybag.png
      - assets/images/shopping-bag.png
      - assets/images/tv.png
      - assets/images/television.png
      - assets/images/home.png
      - assets/images/wifi.png
      - assets/images/homep.png
      - assets/images/hom.png
      - assets/images/bill.png
      - assets/images/ser.png
      - assets/images/pie-chart.png
      - assets/images/splitim.png
      - assets/images/invoice.png
      - assets/images/naira.png
      - assets/images/mag.png
      - assets/images/credit-card.png
      - assets/images/qr-code.png
      - assets/images/bank-building.png
      - assets/images/smile.png
      - assets/images/gif.png
      - assets/images/nearby.png
      - assets/images/padlock.png
      - assets/images/arroba.png
      - assets/images/past.png
      - assets/images/edit.png
      - assets/images/qrcd.png
      - assets/images/mtn.png
      - assets/images/airtel.png
      - assets/images/airte.png
      - assets/images/glo.png
      - assets/images/9mobile.png
      - assets/images/addnum.png
      - assets/images/cle.png
      - assets/images/user.png
      - assets/images/logout.png
      - assets/images/previous.png
      - assets/images/em.png
      - assets/images/chec.png
      - assets/images/like.png
      - assets/images/comment.png
      - assets/images/addphoto.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
